import { Inter } from 'next/font/google'
import MobileNav from '@/components/mobile-nav'
import Sidebar from '@/components/sidebar/sidebar'
import { Toaster } from '@/components/ui/toaster'
import '@/styles/globals.css'
import Providers from './providers'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
})

export const metadata = {
  title: 'Snippy',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable} flex flex-col md:flex-row`}>
        <Providers>
          <Sidebar />
          {children}
          <MobileNav />
          <Toaster />
        </Providers>
      </body>
    </html>
  )
}
